<table align="left"><tr><td>
<a href="https://colab.research.google.com/github/kikim6114/nlp2026/blob/main/python_tutorial/00-9 PyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="코랩에서 실행하기"/></a>
</td></tr></table>

# PyTorch Tutorial 

## 소개
[PyTorch](https://pytorch.org/)는 딥러닝 프레임워크로, [TensorFlow](https://www.tensorflow.org/)와 함께 두 개의 주요 프레임워크 중 하나이다. 설치는 Pip 또는 Conda를 통해 할 수 있으며, 자세한 내용은 [여기](https://pytorch.org/)에서 확인할 수 있다. PyTorch를 가져오는 것으로 시작해 보자:

In [ ]:
import torch
import torch.nn as nn

# pprint를 가져온다. 이 모듈은 출력문을 더 예쁘게 만들어 준다
import pprint
pp = pprint.PrettyPrinter() 

## 파트 1: 텐서
**텐서**는 PyTorch의 가장 기본적인 구성 요소이다. 각 텐서는 다차원 행렬이다. 예를 들어, 256x256 크기의 정사각형 이미지는 `3x256x256` 텐서로 표현될 수 있으며, 여기서 첫 번째 차원은 색상을 나타냅니다. 텐서를 생성하는 방법은 다음과 같다:

In [2]:
list_of_lists = [
  [1, 2, 3],
  [4, 5, 6],
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [3]:
data = torch.tensor(list_of_lists)
print(data)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
# Initializing a tensor
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


각 텐서에는 **데이터 타입**이 있다. 주로 신경 써야 할 데이터 타입은 실수형(`torch.float32`)과 정수형(`torch.int`)이다. 텐서를 생성할 때 데이터 타입을 명시적으로 지정할 수 있다:

In [ ]:
# 명시적인 데이터 타입으로 텐서 초기화
# 숫자 뒤의 점은 실수형임을 나타낸다
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


In [ ]:
# 명시적인 데이터 타입으로 텐서 초기화
# 숫자 뒤의 점은 실수형임을 나타낸다
data = torch.tensor([
                     [0.11111111, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32) #정밀도가 중요한 경우 float64 소수점 정밀도에 따라 사용 
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


In [ ]:
# 명시적인 데이터 타입으로 텐서 초기화
# 숫자 뒤의 점은 실수형임을 나타낸다
data = torch.tensor([
                     [0.11111111, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


주어진 형태와 내용을 가진 텐서를 생성하는 유틸리티 함수도 존재한다:

In [8]:
zeros = torch.zeros(2, 5)  # a tensor of all zeros
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
ones = torch.ones(3, 4)   # a tensor of all ones
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [10]:
rr = torch.arange(1, 10) # range from [1, 10)
print(rr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [11]:
rr + 2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
a = torch.tensor([[1, 2], [2, 3], [4, 5]])      # (3, 2)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])  # (2, 4)

print("A is", a)
print("B is", b)
print("The product is", a.matmul(b)) #(3, 4) 행렬곱 연산
print("The other product is", a @ b) # +, -, *, @(행렬곱 연산자)

A is tensor([[1, 2],
        [2, 3],
        [4, 5]])
B is tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
The product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])
The other product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


행렬의 **형태**(`.shape`로 접근 가능)는 행렬의 차원으로 정의된다. 몇 가지 예시를 보겠다:

In [14]:
matr_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matr_2d.shape)
print(matr_2d)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
matr_3d = torch.tensor([[[1, 2, 3, 4], [-2, 5, 6, 9]], [[5, 6, 7, 2], [8, 9, 10, 4]], [[-3, 2, 2, 1], [4, 6, 5, 9]]])
print(matr_3d)
print(matr_3d.shape)

tensor([[[ 1,  2,  3,  4],
         [-2,  5,  6,  9]],

        [[ 5,  6,  7,  2],
         [ 8,  9, 10,  4]],

        [[-3,  2,  2,  1],
         [ 4,  6,  5,  9]]])
torch.Size([3, 2, 4])


**재구성**(Reshaping)은 배치 연산을 더 쉽게 만들기 위해 사용될 수 있지만, 데이터가 예상한 순서대로 재구성되는지 주의해야 한다:

In [16]:
rr = torch.arange(1, 16)
print("The shape is currently", rr.shape)
print("The contents are currently", rr)
print()
rr = rr.view(5, 3)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr)

The shape is currently torch.Size([15])
The contents are currently tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

After reshaping, the shape is currently torch.Size([5, 3])
The contents are currently tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


마지막으로, 텐서를 **NumPy 배열**과 상호 변환할 수도 있다:

In [17]:
import numpy as np

# numpy.ndarray --> torch.Tensor:
arr = np.array([[1, 0, 5]])
data = torch.tensor(arr)
print("This is a torch.tensor", data)

# torch.Tensor --> numpy.ndarray:
new_arr = data.numpy()
print("This is a np.ndarray", new_arr)

This is a torch.tensor tensor([[1, 0, 5]], dtype=torch.int32)
This is a np.ndarray [[1 0 5]]


우리가 **텐서**를 사용하는 이유 중 하나는 *벡터화 연산*이다: 텐서의 특정 차원에 대해 병렬로 수행할 수 있는 연산이다.

In [18]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)
print("Data is:", data)

# We can perform operations like *sum* over each row...
print("Taking the sum over rows:") # 행 합 연산
print(data.sum(dim=1)) #(5,)

# or over each column.
print("Taking thep sum over columns:") # 열 합 연산
print(data.sum(dim=0)) #(7,)

# Other operations are available:
print("Taking the stdev over rows:") # 행의 표준편차
print(data.std(dim=1))


Data is: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19., 20., 21.],
        [22., 23., 24., 25., 26., 27., 28.],
        [29., 30., 31., 32., 33., 34., 35.]])
Taking the sum over rows:
tensor([ 28.,  77., 126., 175., 224.])
Taking thep sum over columns:
tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])
Taking the stdev over rows:
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [19]:
data = torch.arange(1, 7, dtype=torch.float32).reshape(1, 2, 3) # 배치 크기기 , 2행3열
print(data)
print(data.sum(dim=0).sum(dim=0))
print(data.sum(dim=0).sum(dim=0).shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
tensor([5., 7., 9.])
torch.Size([3])


In [20]:
data.sum()

tensor(21.)

### 퀴즈
다음 내용을 가진 `torch.tensor`를 생성하는 코드를 작성하라:
$\begin{bmatrix} 1 & 2.2 & 9.6 \\\\ 4 & -7.2 & 6.3 \end{bmatrix}$

이제 각 행과 열의 평균(`.mean()`)을 계산하라.

결과의 형태는 무엇인가요?

In [21]:
import torch

# 실수값이 섞여 있으므로 dtype은 float32로 자동 설정됨
x = torch.tensor([
    [1.0, 2.2, 9.6],
    [4.0, -7.2, 6.3]
])

print("Tensor:\n", x)

row_means = x.mean(dim=1)
print("Row means:", row_means)
print("Shape of row means:", row_means.shape)

col_means = x.mean(dim=0)
print("Column means:", col_means)
print("Shape of column means:", col_means.shape)


Tensor:
 tensor([[ 1.0000,  2.2000,  9.6000],
        [ 4.0000, -7.2000,  6.3000]])
Row means: tensor([4.2667, 1.0333])
Shape of row means: torch.Size([2])
Column means: tensor([ 2.5000, -2.5000,  7.9500])
Shape of column means: torch.Size([3])


**인덱싱**

텐서의 임의 요소에 접근하려면 `[]` 연산자를 사용할 수 있다.

In [22]:
# Initialize an example tensor
x = torch.Tensor([
                  [[1, 2], [3, 4]],
                  [[5, 6], [7, 8]],
                  [[9, 10], [11, 12]]
                 ])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [23]:
x.shape

torch.Size([3, 2, 2])

In [ ]:
# 0번째 요소에 접근, 이는 첫 번째 행이다
x[0] # Equivalent to x[0, :]

tensor([[1., 2.],
        [3., 4.]])

In [25]:
x[:, 0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

`:`를 사용해 여러 차원에 인덱싱할 수도 있다.

In [ ]:
# 텐서의 각 요소에서 좌상단 요소를 가져온다
x[:, 0, 0]

tensor([1., 5., 9.])

In [28]:
x[:, :, :]

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

각 차원에서 임의의 요소에 접근할 수도 있다.

In [26]:
# 0번째와 1번째 요소를 각각 두 번씩 접근한다
# x[0], x[0], x[1], x[1]을 쌓는 것과 동일
i = torch.tensor([0, 0, 1, 1])
x[i]

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[5., 6.],
         [7., 8.]]])

In [27]:
# 1번째와 2번째 요소의 0번째 요소에 접근한다

i = torch.tensor([1, 2])
j = torch.tensor([0])
x[i, j]

tensor([[ 5.,  6.],
        [ 9., 10.]])

텐서에서 `Python` 스칼라 값을 얻으려면 `item()`을 사용할 수 있다.

In [28]:
x[0, 0, 0]

tensor(1.)

In [29]:
x[0, 0, 0].item()

1.0

### 연습 문제:

다음 내용을 가진 `torch.tensor`를 생성하는 코드를 작성하라:
$\begin{bmatrix} 1 & 2.2 & 9.6 \\\\ 4 & -7.2 & 6.3 \end{bmatrix}$

첫 번째 열과 첫 번째 행을 어떻게 가져오나요?

## 자동 미분 (Autograd)
Pytorch는 자동 미분 기능으로 잘 알려져 있다. `backward()` 메서드를 호출하여 PyTorch가 기울기를 계산하도록 요청할 수 있으며, 계산된 기울기는 `grad` 속성에 저장된다.

In [30]:
# 예제 텐서 생성
# requires_grad 매개변수는 PyTorch에게 기울기를 저장하도록 지시한다
x = torch.tensor([2.], requires_grad=True)

# Print the gradient if it is calculated
# Currently None since x is a scalar
pp.pprint(x.grad)

None


In [31]:
# x에 대한 y의 기울기 계산
y = x * x * 3 # 3x^2
y.backward()
pp.pprint(x.grad) # d(y)/d(x) = d(3x^2)/d(x) = 6x = 12

tensor([12.])


다른 텐서에서 다시 역전파를 실행하여 어떤 일이 발생하는지 확인해 보자.

In [32]:
z = x * x * 3 # 3x^2
z.backward()
pp.pprint(x.grad)

tensor([24.])


In [33]:
x.grad = None
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([12.])


In [34]:
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([24.])


In [35]:
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([36.])


## 신경망 학습 시 .zero_grad()가 꼭 필요한 이유
- `x.grad`는 지금까지 계산된 그래디언트들의 합으로 업데이트됨
- `.backward()`를 여러 번 호출하면 그 결과가 누적됨. 역전파의 기본구조 때문에 신경망에서는 하나의 뉴런에 여러 경로를 통해 전달된 기울기를 모두 더한 후 가중치를 업데이트
- 매번 학습할 때마다 `zero_grad()`를 호출해서 이전 기울기 값을 초기화해야 함 그렇지 않으면 기울기 누적으로 인해 잘못된 방향으로 학습될 수 있음

## Customized Backward Function  
PyTorch에서 기본적으로 지원하지 않는 **고차 기울기**(higher-order gradients)을 계산하고 싶을 경우,  
직접 `forward`와 `backward` 연산을 정의한 **사용자 정의 함수**(Custom Function)를 만들 수 있음  

사용 사례:
- **새로운 수식이나 연산을 직접 구현**할 때  
  - (예) 논문에서 제안된 특이한 연산자
- **고차 미분**(예: 미분의 미분, 2차 미분)을 정확히 컨트롤하고 싶을 때
- PyTorch의 **기본 연산자보다 더 최적화된 구현**을 하고 싶을 때  
 (참고: https://pytorch.org/docs/stable/notes/extending.html)

## Neural Network Module

지금까지 우리는 텐서(tensor), 그 속성들, 그리고 텐서에 대한 기본 연산들을 살펴보았다.  
이러한 내용은 **신경망의 층을 처음부터 직접 구현할 때** 특히 유용하다.   
앞으로는 PyTorch의 `torch.nn` 모듈에 포함된 **미리 정의된 블록(predefined blocks)**을 사용할 것이다.  

이러한 블록들을 조합하여 **복잡한 신경망을 구성**하게 된다.  
먼저, 매번 `torch`를 타이핑하지 않도록, 이 모듈을 **별칭(alias)**으로 불러오는 것부터 시작하겠다.


In [39]:
import torch.nn as nn

### **Linear Layer**
### Linear Layer (선형 계층)

**선형 계층(Linear layer)**은 기본적으로 **행렬 곱셈과 편향(bias) 덧셈**을 수행하는 연산을 정의한다.  
즉, 입력 `x`에 대해 아래 연산을 실행한다:

\[
Ax + b
\]

여기서:  
- `A`는 **가중치 행렬 (weight matrix)**  
- `b`는 **편향 벡터 (bias vector)**  

PyTorch에서는 `nn.Linear`를 생성할 때, **가중치 `A`와 편향 `b`를 무작위(random)** 값으로 초기화한다.

---

### 입력 차원

`nn.Linear(H_i, H_o)`는 입력의 **마지막 차원**이 `H_i`인 데이터를 받아서, **마지막 차원을 `H_o`로 변환**한다.

입력 텐서는 보통 다음과 같은 형태를 가진다:

\[
(N, *, H_i)
\]

- `N`: 일반적으로 **배치 크기(batch size)**를 의미  
- `*`: 중간에 올 수 있는 임의의 다른 차원들. 이들은 선형 변환 전에 **평면화(flatten)**되지 않고 그대로 유지된다.  
- `H_i`: **입력 벡터의 크기**, 즉 마지막 차원의 크기


In [40]:
# 입력 생성
input = torch.ones(2,3,4)
# N* H_in -> N*H_out


# N,*,H_in 차원의 입력을 N,*,H_out 차원의 출력으로 변환하는 선형 레이어 생성
linear = nn.Linear(4, 2) 
linear_output = linear(input)
linear_output

tensor([[[-0.1035, -0.6379],
         [-0.1035, -0.6379],
         [-0.1035, -0.6379]],

        [[-0.1035, -0.6379],
         [-0.1035, -0.6379],
         [-0.1035, -0.6379]]], grad_fn=<ViewBackward0>)

In [41]:
linear_output.shape

torch.Size([2, 3, 2])

In [42]:
list(linear.parameters()) # Ax + b

[Parameter containing:
 tensor([[-0.1646, -0.3147,  0.3458,  0.2793],
         [-0.3891, -0.1266, -0.3497,  0.1239]], requires_grad=True),
 Parameter containing:
 tensor([-0.2492,  0.1035], requires_grad=True)]

In [43]:
# [batch_size, feature_dim] 형태의 데이터 # 4
# [batch_size, output_dim] 출력 # 2

# (feature_dim, output_dim) 형태의 선형 레이어

### **Other Module Layers**

PyTorch의 `nn` 모듈에는 **사전에 구성된 다양한 레이어**들이 포함되어 있다.  
이러한 레이어들은 **플러그 앤 플레이(plug-and-play)** 방식으로 사용할 수 있어,  
우리가 필요한 **차원 정보만 입력**해주면 나머지는 PyTorch가 자동으로 처리해준다.

---

### 자주 사용되는 레이어들

| 레이어 | 설명 |
|--------|------|
| `nn.Conv2d` | **2D 합성곱 레이어** (이미지 처리에 주로 사용) |
| `nn.ConvTranspose2d` | **Conv2d의 역방향 연산** (업샘플링, 이미지 복원) |
| `nn.BatchNorm1d/2d` | **배치 정규화** (학습 안정성 향상, 과적합 방지) |
| `nn.Upsample` | **이미지 사이즈 확대** (보간법(interpolation) 사용) |
| `nn.MaxPool2d` | **최대 풀링** (특징 요약, 차원 축소에 사용) |


### **Activation Function Layer**
nn 모듈을 통해 활성화 함수를 텐서에 적용하여 신경망에 **비선형성(non-linearity)**을 더해줌 활성화 함수는 입력 텐서의 각 원소마다 독립적으로 작동하여 입력과 출력의 shape이 동일

In [44]:
linear_output

tensor([[[-0.1035, -0.6379],
         [-0.1035, -0.6379],
         [-0.1035, -0.6379]],

        [[-0.1035, -0.6379],
         [-0.1035, -0.6379],
         [-0.1035, -0.6379]]], grad_fn=<ViewBackward0>)

In [45]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.4741, 0.3457],
         [0.4741, 0.3457],
         [0.4741, 0.3457]],

        [[0.4741, 0.3457],
         [0.4741, 0.3457],
         [0.4741, 0.3457]]], grad_fn=<SigmoidBackward0>)

### **Putting the Layers Together**
지금까지 우리는 레이어를 만들고, 한 레이어의 출력을 다음 레이어의 입력으로 넘기는 방식을 했음 그런데 이렇게 하면 중간 텐서를 계속 생성하고 넘겨줘야 해서 번거로울 수 있음 그래서 nn.sequential을 사용하여 그 과정을 자동화 처리함

In [46]:
block = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4) # 배치 크기, 시퀀스 길이, 특성
output = block(input)
output

tensor([[[0.4337, 0.2388],
         [0.4337, 0.2388],
         [0.4337, 0.2388]],

        [[0.4337, 0.2388],
         [0.4337, 0.2388],
         [0.4337, 0.2388]]], grad_fn=<SigmoidBackward0>)

### 사용자 정의 모듈 만들기 (Custom Module)

PyTorch에서는 `nn.Linear`, `nn.Conv2d`와 같은 **미리 정의된 모듈** 외에도,  
직접 `nn.Module`을 상속받아 **나만의 모듈(Custom Module)**을 만들 수 있다.  
이 방식은 **복잡한 구조의 모델**을 설계할 때 매우 유용하다.

---

#### 사용자 정의 모듈을 만들기 위한 구성 요소

1. `nn.Module`을 상속  
2. `__init__()` 메서드에서 필요한 구성 요소(레이어 등) 초기화  
3. `forward(x)` 메서드를 **반드시 정의**해야 함

---

#### 학습 가능한 파라미터 자동 등록

`nn.Module`의 속성으로 정의된 다음과 같은 요소들은  
**자동으로 학습 대상 파라미터**로 등록되어 `model.parameters()`에 포함된다:

- `nn.Linear`, `nn.Conv2d`  
- `nn.Parameter`  

즉, 따로 등록할 필요 없이 학습 대상이 된다.

---

#### `nn.Sequential` vs 사용자 정의 모듈

- `nn.Sequential`: 간단하고 빠르게 레이어를 쌓을 때 유용  
- 사용자 정의 모듈: **더 유연한 모델 구성**이 가능  
  - 조건문, 반복문, 병렬 연산 등 복잡한 로직 구현이 필요할 때 적합



In [47]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__() #초기화자 호출을 통해 학습가능한 파라미터 등록,모델 상태 관리,GPU 전송 등 기능 작동

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Defining of our model
    # There isn't anything specific about the naming of `self.model`. It could
    # be something arbitrary.
    self.model = nn.Sequential(
        nn.Linear(self.input_size, self.hidden_size), # 입력 -> 은닉층
        nn.ReLU(), # 비선형성
        nn.Linear(self.hidden_size, self.input_size), # 은닉층 -> 출력
        nn.Sigmoid() # 출력에 시그모이드
    )

  def forward(self, x):
    output = self.model(x) 
    return output

Here is an alternative way to define the same class. You can see that we can replace `nn.Sequential` by defining the individual layers in the `__init__` method and connecting the in the `forward` method.

In [48]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Defining of our layers
    self.linear = nn.Linear(self.input_size, self.hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.input_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    linear = self.linear(x)
    relu = self.relu(linear)
    linear2 = self.linear2(relu)
    output = self.sigmoid(linear2)
    return output

Now that we have defined our class, we can instantiate it and see what it does.

In [49]:
# Make a sample input
input = torch.randn(2, 5) #배치 수, 특성 수

# Create our model
model = MultilayerPerceptron(5, 3) #input_size, hidden_layer

# Pass our input through our model
model(input)

tensor([[0.6056, 0.4050, 0.6174, 0.5342, 0.4261],
        [0.6116, 0.3513, 0.4627, 0.5797, 0.2585]], grad_fn=<SigmoidBackward0>)

We can inspect the parameters of our model with `named_parameters()` and `parameters()` methods.

In [50]:
list(model.named_parameters())

[('linear.weight',
  Parameter containing:
  tensor([[-0.3006,  0.3190, -0.1263, -0.0087,  0.3948],
          [-0.3908,  0.3930, -0.3938,  0.4387, -0.1106],
          [-0.0982,  0.0185, -0.1223,  0.2646,  0.1205]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([-0.3798,  0.0386,  0.2652], requires_grad=True)),
 ('linear2.weight',
  Parameter containing:
  tensor([[ 0.1570, -0.4173,  0.1076],
          [-0.2112,  0.4463, -0.3705],
          [-0.3008, -0.4283, -0.4930],
          [-0.1177, -0.0147,  0.3514],
          [-0.5115, -0.5427, -0.4763]], requires_grad=True)),
 ('linear2.bias',
  Parameter containing:
  tensor([ 0.4288, -0.3848,  0.4784,  0.1371, -0.2979], requires_grad=True))]

### 옵티마이저(Optimizer)의 역할

역전파로 **기울기(gradient)**만 계산된다고 해서 학습이 끝나는 것이 아니다.  
그 **기울기를 바탕으로 실제로 파라미터를 업데이트**하는 것이 바로 **optimizer(최적화 도구)**의 역할이다.

---

### PyTorch 옵티마이저 사용 흐름

1. **옵티마이저 선택**  
   - 예: `SGD`, `Adam` 등

2. **모델의 파라미터 전달**  
   - `model.parameters()`를 통해 전달

3. **학습 루프 내에서 반복 수행**  
   - `optimizer.zero_grad()`  
     → 이전 step의 기울기를 초기화  
   - `loss.backward()`  
     → 현재 step의 **기울기 계산 (역전파)**  
   - `optimizer.step()`  
     → 계산된 기울기를 사용하여 **파라미터 업데이트**


In [51]:
import torch.optim as optim

### 손실 함수(Loss Function) 정의

옵티마이저를 생성한 후에는,  
어떤 **손실(loss)**을 줄이고 싶은지 **정의**해야 한다.

손실 함수를 정의하는 방법은 두 가지가 있다:

1. **손실 함수를 직접 정의**하기  
2. **PyTorch에서 제공하는 손실 함수** 사용  
   - 예: `nn.BCELoss()`, `nn.MSELoss()` 등


In [52]:
# Create the y data
y = torch.ones(10, 5)

# Add some noise to our goal y to generate our x
# We want out model to predict our original data, albeit the noise
x = y + torch.randn_like(y)
x

tensor([[ 1.9420,  0.4419,  0.0895, -0.1043,  0.1553],
        [ 2.6451,  0.8322,  1.1914,  1.2819,  0.2272],
        [ 0.9886,  1.1638,  0.6912,  0.8520,  2.7661],
        [-1.0232, -1.3883,  0.5320,  1.2993,  2.6847],
        [-0.3437,  1.4322,  1.9804,  2.7389,  1.1925],
        [-0.0413,  1.0695,  0.2764,  0.2288,  1.0808],
        [-1.0673,  0.8945,  0.9126,  1.1100,  1.0859],
        [-0.1806,  0.9053,  0.1192,  2.4304,  1.2275],
        [ 0.1360,  1.2003,  1.2485,  0.7760,  2.1443],
        [ 2.8109,  0.3939,  0.3727,  1.8952,  1.9835]])

Now, we can define our model, optimizer and the loss function.

In [53]:
# Instantiate the model
model = MultilayerPerceptron(5, 3)

# Define the optimizer
adam = optim.Adam(model.parameters(), lr=1e-1) # 옵티마이저, lr이 0.1로 비교적 큰 값 

# Define loss using a predefined loss function
loss_function = nn.MSELoss()

# Calculate how our model is doing now
y_pred = model(x)
loss_function(y_pred, y).item()

0.3044360280036926

Let's see if we can have our model achieve a smaller loss. Now that we have everything we need, we can setup our training loop.

In [54]:
# Set the number of epoch, which determines the number of training iterations
n_epoch = 10

for epoch in range(n_epoch):
  # Set the gradients to 0
  adam.zero_grad() # 기울기 계산은 누적되기에

  # Get the model predictions
  y_pred = model(x)

  # Get the loss
  loss = loss_function(y_pred, y)

  # Print stats
  print(f"Epoch {epoch}: traing loss: {loss}")

  # Compute the gradients
  loss.backward()

  # Take a step to optimize the weights
  adam.step()


Epoch 0: traing loss: 0.3044360280036926
Epoch 1: traing loss: 0.25961217284202576
Epoch 2: traing loss: 0.20624488592147827
Epoch 3: traing loss: 0.14851129055023193
Epoch 4: traing loss: 0.09684035927057266
Epoch 5: traing loss: 0.057046521455049515
Epoch 6: traing loss: 0.029874444007873535
Epoch 7: traing loss: 0.013928174041211605
Epoch 8: traing loss: 0.006031113676726818
Epoch 9: traing loss: 0.002541359281167388


In [55]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3114, -0.1611, -0.2988, -0.2735, -0.2439],
         [-0.5746, -0.2528, -0.5971, -0.3205, -0.8126],
         [ 0.8472,  0.9084,  1.0264,  0.4904,  0.9444]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3210, -0.0457,  1.0272], requires_grad=True),
 Parameter containing:
 tensor([[ 1.9782e-01,  5.0830e-01,  1.1815e+00],
         [ 6.4485e-02,  3.3071e-04,  6.2364e-01],
         [ 3.8330e-01,  4.6853e-02,  1.0244e+00],
         [-1.2395e-01,  4.3495e-01,  5.5529e-01],
         [ 2.4076e-01,  1.7973e-01,  1.0316e+00]], requires_grad=True),
 Parameter containing:
 tensor([0.5662, 1.3864, 0.4035, 0.5151, 0.4808], requires_grad=True)]

You can see that our loss is decreasing. Let's check the predictions of our model now and see if they are close to our original `y`, which was all `1s`.

In [56]:
# See how our model performs on the training data
y_pred = model(x)
y_pred

tensor([[0.9881, 0.9683, 0.9769, 0.9110, 0.9791],
        [0.9996, 0.9944, 0.9987, 0.9801, 0.9988],
        [0.9998, 0.9961, 0.9993, 0.9854, 0.9994],
        [0.9749, 0.9534, 0.9563, 0.8775, 0.9601],
        [0.9997, 0.9958, 0.9992, 0.9844, 0.9993],
        [0.9896, 0.9705, 0.9795, 0.9162, 0.9814],
        [0.9904, 0.9716, 0.9807, 0.9188, 0.9826],
        [0.9959, 0.9818, 0.9908, 0.9443, 0.9917],
        [0.9995, 0.9938, 0.9985, 0.9782, 0.9986],
        [0.9998, 0.9967, 0.9995, 0.9876, 0.9995]], grad_fn=<SigmoidBackward0>)

In [57]:
# Create test data and check how our model performs on it
x2 = y + torch.randn_like(y)
y_pred = model(x2)
y_pred

tensor([[0.9995, 0.9937, 0.9984, 0.9777, 0.9986],
        [0.9998, 0.9958, 0.9992, 0.9845, 0.9993],
        [0.9934, 0.9766, 0.9861, 0.9312, 0.9874],
        [0.9999, 0.9971, 0.9996, 0.9890, 0.9996],
        [0.9882, 0.9684, 0.9770, 0.9112, 0.9792],
        [0.9804, 0.9590, 0.9646, 0.8897, 0.9678],
        [0.9998, 0.9964, 0.9994, 0.9866, 0.9995],
        [0.9891, 0.9696, 0.9788, 0.9130, 0.9806],
        [0.9983, 0.9886, 0.9957, 0.9628, 0.9962],
        [0.9999, 0.9974, 0.9996, 0.9898, 0.9997]], grad_fn=<SigmoidBackward0>)

Great! Looks like our model almost perfectly learned to filter out the noise from the `x` that we passed in!

### 데모: Word Window Classification: 단어 단위 문맥 분류

문장 속 하나의 단어만을 보는 것으로는 부족하기 때문에,  
**단어 주변의 문맥(context)**을 함께 고려해야 한다.  
이를 위해 **Word Window Classification**이라는 고전적인 기법을 사용하여  
**단어 단위로 위치 정보(Location)**를 분류하는 문제를 해결한다.

---

### 문제 정의

- **목표**: 문장에서 각 단어가 `LOCATION`인지 아닌지를 판단하는 모델 생성
- **가정**: `LOCATION`은 항상 **한 단어짜리**만 존재 (예: `Paris`는 OK, `San Francisco`는 X)

---

### 데이터 만들기

- 각 단어에 대해 `"앞 단어, 현재 단어, 뒤 단어"`로 이루어진 **윈도우(window)** 생성
- 각 윈도우는 **하나의 입력**으로 사용되며,  
  **중앙 단어의 레이블**(LOCATION 여부)을 예측

---

### 모델링

- **입력**: 윈도우 내 단어들의 벡터(임베딩 또는 원-핫)
- **출력**: 중앙 단어가 `LOCATION`인지 아닌지를 판별하는 **이진 분류(binary classification)**

---

### 훈련

- **손실 함수**:
  - `nn.BCELoss()` 또는 `nn.CrossEntropyLoss()`  
- **옵티마이저**:
  - `Adam`, `SGD` 등

---

### 예측

- 문장을 입력으로 받아서  
  각 단어가 **LOCATION**인지 여부를 **순서대로 판단**


### Data

모든 머신 러닝 프로젝트의 첫 번째 작업은 훈련 세트를 설정하는 것이다. 일반적으로 사용할 훈련 코퍼스가 있을 것이다. NLP 작업에서 코퍼스는 일반적으로 각 행이 문장이나 테이블 형식 데이터 포인트에 해당하는 `.txt` 또는 `.csv` 파일이다. 이 간단한 작업에서는 데이터와 해당 레이블을 이미 `Python` 리스트로 읽었다고 가정하겠다.

In [58]:
# Our raw data, which consists of sentences
corpus = [
          "We always come to Paris",
          "The professor is from Australia",
          "I live in Stanford",
          "He comes from Taiwan",
          "The capital of Turkey is Ankara"
         ]

### 전처리(Preprocessing)의 중요성

분석의 목적에 따라 어떤 전처리 과정을 수행할지가 결정되므로,  
**전처리 과정은 자연어 처리에서 필수적인 단계**이다.

---

### 주요 전처리 단계

1. **Tokenization (토크나이징)**  
   - 문장을 **단어 단위로 분리**  
   - 예: `"I love Paris"` → `["I", "love", "Paris"]`

2. **Lowercasing (소문자 변환)**  
   - 대소문자 구분 없이 처리하기 위해 **모든 단어를 소문자**로 변환  
   - 예: `"Paris"` → `"paris"`

3. **Noise removal (노이즈 제거)**  
   - 모델 학습에 방해되는 **특수문자, 기호, 이모지** 등을 제거  
   - 예: `"hello! 😊"` → `"hello"`

4. **Stop words removal (불용어 제거)**  
   - 자주 등장하지만 **정보량이 적은 단어들** 제거  
   - 예: `a`, `the`, `is`, `in`, `on`, ...

---

이러한 전처리 과정을 통해 **데이터의 품질을 높이고, 모델 성능 향상**에 기여할 수 있다.


In [59]:
# 훈련 예제를 생성하기 위해 사용할 전처리 함수
# 이 함수는 간단하게 글자를 소문자로 바꾸고 단어를 토큰화한다.
def preprocess_sentence(sentence):
  return sentence.lower().split() #띄어쓰기 기준으로 구분 

# Create our training set
train_sentences = [preprocess_sentence(sent) for sent in corpus]
train_sentences

[['we', 'always', 'come', 'to', 'paris'],
 ['the', 'professor', 'is', 'from', 'australia'],
 ['i', 'live', 'in', 'stanford'],
 ['he', 'comes', 'from', 'taiwan'],
 ['the', 'capital', 'of', 'turkey', 'is', 'ankara']]

각 훈련 예제마다 해당 레이블도 있어야 한다. 모델의 목표가 어떤 단어가 `LOCATION`에 해당하는지 결정하는 것임을 상기하라. 즉, 모델이 `LOCATION`이 아닌 모든 단어에 대해 `0`을 출력하고, `LOCATION`인 단어에 대해 `1`을 출력하기를 원한다.

In [60]:
# Set of locations that appear in our corpus
locations = set(["australia", "ankara", "paris", "stanford", "taiwan", "turkey"])

# Our train labels
train_labels = [[1 if word in locations else 0 for word in sent] for sent in train_sentences]
train_labels

[[0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1, 0, 1]]

### Converting Words to Embeddings (단어를 임베딩으로 변환)

우리의 입력은 `"paris"`, `"live"`처럼 **문자열 형태의 단어**이지만,  
머신러닝/딥러닝 모델은 **숫자 벡터**로만 연산이 가능하기 때문에  
**문자열을 숫자로 변환**하는 과정이 필요한다.

---

임베딩 조회 테이블 `E`가 있다고 상상해 보자. 여기서 각 행은 임베딩에 해당한다. 즉, 어휘에 있는 각 단어는 이 테이블에서 해당하는 임베딩 행 `i`를 갖습니다. 단어의 임베딩을 찾으려면 다음 단계를 따른다:
1. 임베딩 테이블에서 단어의 해당 인덱스 `i`를 찾는다: `word->index`.
2. 임베딩 테이블에 인덱싱하여 임베딩을 얻는다: `index->embedding`.

첫 번째 단계를 살펴보자. 어휘에 있는 모든 단어에 해당 인덱스를 지정해야 한다. 다음과 같이 할 수 있다:
1. 코퍼스에서 모든 고유 단어를 찾는다.
2. 각 단어에 인덱스를 지정한다.

In [61]:
# Find all the unique words in our corpus
vocabulary = set(w for s in train_sentences for w in s)
vocabulary

{'always',
 'ankara',
 'australia',
 'capital',
 'come',
 'comes',
 'from',
 'he',
 'i',
 'in',
 'is',
 'live',
 'of',
 'paris',
 'professor',
 'stanford',
 'taiwan',
 'the',
 'to',
 'turkey',
 'we'}

### Out-of-Vocabulary (OOV) 단어 처리

현재의 **vocabulary**(어휘 사전)는 우리가 가진 말뭉치(corpus)에 등장한 모든 단어들을 포함하고 있다.  
하지만 **테스트 시점**(test time)에는 **어휘 사전에 없는 단어들**(out-of-vocabulary, OOV)을 마주칠 수 있다.

---

### 왜 OOV 처리가 필요한가?

모델은 예측 시에 **중심 단어 뿐만 아니라 주변 단어들의 문맥**도 함께 보기 때문에, **알 수 없는 단어라도 그 주변 문맥을 통해 의미를 추론**할 수 있다.

→ 따라서, OOV 단어를 완전히 배제하지 않고, 대신 **특수 토큰** `<unk>`(unknown)으로 대체해 처리한다.

---

### `<unk>` 토큰의 역할

- 어휘 사전에 없는 모든 단어는 `<unk>` 토큰으로 대체됨
- 이 토큰은 **고유하게만 설정**되어 있다면 이름은 꼭 `<unk>`일 필요는 없음  
  - 예: `<unknown>`, `[UNK]`, `@@unk@@` 등

---

이렇게 하면 **모델이 학습되지 않은 단어**가 등장하더라도 일관된 방식으로 처리할 수 있으며, 문맥 기반으로 충분히 예측이 가능해진다.


In [62]:
# Add the unknown token to our vocabulary
vocabulary.add("<unk>")

### 왜 Word Window Classification인가?

우리는 앞서 이 과제가 **Word Window Classification**이라고 불리는 이유에 대해 언급한 적이 있다.  
그 이유는, **모델이 단어를 예측할 때 해당 단어뿐만 아니라 그 주변 단어들까지 함께 고려하기 때문**이다.

---

### 예시 문장: `"We always come to Paris"`

- 정답 레이블: `[0, 0, 0, 0, 1]`  
- 이유: 오직 마지막 단어 `"Paris"`만 **LOCATION (장소명)**이기 때문

---

### 단어 하나만 보면 안 되는 이유

모델이 `"Paris"` 하나만 보고 예측하게 된다면,  
예를 들어 `"to"`라는 단어가 자주 LOCATION 앞에 등장한다는  
**중요한 문맥 정보**를 활용할 수 없다.

→ **그래서 Word Window라는 개념을 도입**한다.

---

### Word Window 개념

- 예측 시, 중심 단어 기준으로 **앞뒤 N개의 단어 (총 2N + 1개)**를 함께 고려
- 윈도우 크기(`window size`)가 1이라면:
  - 입력 단어 수: 앞 1, 중심 1, 뒤 1 → **총 3개의 단어**

#### 예시 (윈도우 크기 = 1):
중심 단어 `"Paris"` → 입력: `["to", "Paris", <pad>]`  
(※ `"Paris"`는 문장의 마지막 단어이므로 뒤 단어가 없음)

---

### 고정된 입력 크기의 문제

PyTorch 모델을 초기화할 때는 입력 크기를 **미리 고정**해야 한다.  
하지만 문장의 처음이나 끝에 위치한 단어들은 **윈도우의 일부가 부족**할 수 있다.

→ 예: `"Paris"`는 마지막 단어이므로 뒤 단어가 없음  
→ 예: `"We"`는 첫 단어이므로 앞 단어가 없음

---

### 해결책: `<pad>` 토큰

- 문장의 앞과 뒤에 `<pad>` 같은 **특수 토큰**을 추가
- 모든 단어가 항상 **고정된 윈도우 크기**를 유지할 수 있도록 보장

이렇게 하면 모델은 **항상 동일한 입력 크기**로 데이터를 받아 처리할 수 있다.


In [63]:
# Add the <pad> token to our vocabulary
vocabulary.add("<pad>")

# Function that pads the given sentence
# We are introducing this function here as an example
# We will be utilizing it later in the tutorial
def pad_window(sentence, window_size, pad_token="<pad>"):
  window = [pad_token] * window_size
  return window + sentence + window

# Show padding example
window_size = 2
pad_window(train_sentences[0], window_size=window_size)

['<pad>', '<pad>', 'we', 'always', 'come', 'to', 'paris', '<pad>', '<pad>']

Now that our vocabularly is ready, let's assign an index to each of our words.

In [64]:
# We are just converting our vocabularly to a list to be able to index into it
# Sorting is not necessary, we sort to show an ordered word_to_ind dictionary
# That being said, we will see that having the index for the padding token
# be 0 is convenient as some PyTorch functions use it as a default value
# such as nn.utils.rnn.pad_sequence, which we will cover in a bit
# <pad>의 index값은 0
ix_to_word = sorted(list(vocabulary))

# Creating a dictionary to find the index of a given word
word_to_ix = {word: ind for ind, word in enumerate(ix_to_word)}
word_to_ix

{'<pad>': 0,
 '<unk>': 1,
 'always': 2,
 'ankara': 3,
 'australia': 4,
 'capital': 5,
 'come': 6,
 'comes': 7,
 'from': 8,
 'he': 9,
 'i': 10,
 'in': 11,
 'is': 12,
 'live': 13,
 'of': 14,
 'paris': 15,
 'professor': 16,
 'stanford': 17,
 'taiwan': 18,
 'the': 19,
 'to': 20,
 'turkey': 21,
 'we': 22}

In [65]:
ix_to_word[1]

'<unk>'

Great! We are ready to convert our training sentences into a sequence of indices corresponding to each token.

In [66]:
# Given a sentence of tokens, return the corresponding indices
def convert_token_to_indices(sentence, word_to_ix):
  indices = []
  for token in sentence:
    # Check if the token is in our vocabularly. If it is, get it's index.
    # If not, get the index for the unknown token.
    if token in word_to_ix:
      index = word_to_ix[token]
    else:
      index = word_to_ix["<unk>"] # 단어가 없을 경우
    indices.append(index)
  return indices

# More compact version of the same function
def _convert_token_to_indices(sentence, word_to_ix):
  return [word_to_ind.get(token, word_to_ix["<unk>"]) for token in sentence]

# Show an example
example_sentence = ["we", "always", "come", "to", "kuwait"]
example_indices = convert_token_to_indices(example_sentence, word_to_ix)
restored_example = [ix_to_word[ind] for ind in example_indices]

print(f"Original sentence is: {example_sentence}")
print(f"Going from words to indices: {example_indices}")
print(f"Going from indices to words: {restored_example}")

Original sentence is: ['we', 'always', 'come', 'to', 'kuwait']
Going from words to indices: [22, 2, 6, 20, 1]
Going from indices to words: ['we', 'always', 'come', 'to', '<unk>']


In the example above, `kuwait` shows up as `<unk>`, because it is not included in our vocabulary. Let's convert our `train_sentences` to `example_padded_indices`.

In [67]:
# Converting our sentences to indices
example_padded_indices = [convert_token_to_indices(s, word_to_ix) for s in train_sentences]
example_padded_indices

[[22, 2, 6, 20, 15],
 [19, 16, 12, 8, 4],
 [10, 13, 11, 17],
 [9, 7, 8, 18],
 [19, 5, 14, 21, 12, 3]]

이제 각 단어에 대한 인덱스가 있으므로, PyTorch의 `nn.Embedding` 클래스를 사용하여 임베딩 테이블을 만들 수 있다. 이는 `nn.Embedding(num_words, embedding_dimension)`로 호출되며, 여기서 `num_words`는 어휘의 단어 수이고 `embedding_dimension`은 원하는 임베딩 차원이다. `nn.Embedding`에는 특별한 점이 없다: 이는 단지 학습 가능한 `NxE` 차원 텐서를 감싸는 래퍼 클래스일 뿐이다. 여기서 `N`은 어휘의 단어 수이고 `E`는 임베딩 차원 수이다. 이 테이블은 처음에는 무작위이지만, 시간이 지나면서 변할 것이다. 네트워크를 훈련시키면서 기울기가 임베딩 레이어까지 역전파되어 단어 임베딩이 업데이트된다. 모델에서 사용할 임베딩 레이어를 모델에서 초기화할 것이지만, 여기서 예제를 보여준다.

In [68]:
# Creating an embedding table for our words
embedding_dim = 5
embeds = nn.Embedding(len(vocabulary), embedding_dim)

# Printing the parameters in our embedding table
list(embeds.parameters())

[Parameter containing:
 tensor([[-1.5515,  0.5198, -0.6732, -0.7327,  0.3340],
         [ 1.2022, -1.5715,  0.1017, -1.7680, -0.9001],
         [ 0.1969,  0.7469, -0.0420, -0.6972,  0.4159],
         [ 0.8774, -0.2714,  1.0569,  1.1495, -0.6025],
         [ 1.8619, -0.4599,  0.6227,  0.4261, -0.9787],
         [-0.8487, -1.1778,  0.3496,  0.1602,  1.2061],
         [ 1.2566,  0.8215,  0.4857,  0.2819, -0.7380],
         [ 0.1584, -0.6932,  0.5469, -0.3502, -1.2484],
         [-1.2314,  1.6259, -2.4014,  0.2494,  1.3384],
         [ 0.9551, -0.5706, -1.0833,  0.3072,  0.8559],
         [ 0.5687,  1.7093,  0.3632,  1.2664,  0.4176],
         [ 0.1429, -0.0726, -0.4393, -0.8485,  0.1150],
         [ 0.5393, -0.8393, -1.3340,  0.0211, -0.3929],
         [ 1.8459, -1.0584, -0.1952,  1.8326, -0.1767],
         [ 0.6626, -0.9405, -0.9285,  0.9845, -0.7405],
         [-0.6940,  1.0421, -1.4112,  1.2019,  0.2392],
         [ 0.3371,  1.0839, -0.0489, -0.2501,  2.2884],
         [-1.5639, -0.659

어휘에 있는 단어의 임베딩을 얻으려면 조회 텐서를 만들기만 하면 된다. 조회 텐서는 우리가 조회하려는 인덱스를 포함하는 텐서일 뿐이다. `nn.Embedding` 클래스는 Long Tensor 타입의 인덱스 텐서를 기대하므로, 이에 맞춰 텐서를 만들어야 한다.

In [69]:
# Get the embedding for the word Paris
index = word_to_ix["paris"] # 숫자 변환 
index_tensor = torch.tensor(index, dtype=torch.long) # tesor를 필요로 함 
paris_embed = embeds(index_tensor)
paris_embed

tensor([-0.6940,  1.0421, -1.4112,  1.2019,  0.2392],
       grad_fn=<EmbeddingBackward0>)

In [70]:
# We can also get multiple embeddings at once
index_paris = word_to_ix["paris"]
index_ankara = word_to_ix["ankara"]
indices = [index_paris, index_ankara]
indices_tensor = torch.tensor(indices, dtype=torch.long)
embeddings = embeds(indices_tensor)
embeddings

tensor([[-0.6940,  1.0421, -1.4112,  1.2019,  0.2392],
        [ 0.8774, -0.2714,  1.0569,  1.1495, -0.6025]],
       grad_fn=<EmbeddingBackward0>)

Usually, we define the embedding layer as part of our model, which you will see in the later sections of our notebook.

### 학습 방식: 한 문장씩이 아닌 "배치 단위"로 학습하기

지금까지는 모델 학습을 **"한 문장씩" 처리**하는 방식으로 진행했다.  
하지만 실제 딥러닝에서는 보통 다음의 세 가지 방식 중 하나를 선택한다.

---

### 1. 전체 데이터를 한꺼번에 처리 (Batch Gradient Descent)

- **모든 데이터를 사용해 한 번에 평균 손실(loss)**을 구하고 파라미터 업데이트
- **장점**: 가장 **안정적인 경사(gradient)** 계산 가능  
- **단점**: 데이터가 많을 경우 **속도가 느리고, GPU 메모리 초과** 가능성 있음

---

### 2. 데이터 하나씩 처리 (Stochastic Gradient Descent, SGD)

- **한 문장, 한 예제마다** 파라미터를 바로 업데이트  
- **장점**: 빠르게 학습 시작 가능  
- **단점**: **계산이 불안정**, 손실이 크게 출렁일 수 있음

---

### 3. 적절한 해결책: 미니배치 (Mini-batch Gradient Descent)

- 여러 개의 예제를 묶어 **"배치(batch)" 단위로 학습**
- **장점**:
  - 전체보다는 **빠르고**
  - 개별보다 **안정적인** 경사 계산 가능  
- **PyTorch에서는 `DataLoader`**라는 도구를 통해  
  **미니배치 학습을 쉽게 구현**할 수 있음

---

💡 결론: **속도와 안정성의 균형**을 위해 대부분의 딥러닝 모델은 **Mini-batch 방식**을 사용한다.


In [71]:
from torch.utils.data import DataLoader
from functools import partial

def custom_collate_fn(batch, window_size, word_to_ix):
  # Break our batch into the training examples (x) and labels (y)
  # We are turning our x and y into tensors because nn.utils.rnn.pad_sequence
  # method expects tensors. This is also useful since our model will be
  # expecting tensor inputs.
  x, y = zip(*batch) # 배치를 입력과 라벨로 분류 (sentence,label)형태의 튜플일 것이기 때문에

  # Now we need to window pad our training examples. We have already defined a
  # function to handle window padding. We are including it here again so that
  # everything is in one place.
  def pad_window(sentence, window_size, pad_token="<pad>"):
    window = [pad_token] * window_size
    return window + sentence + window

  # Pad the train examples.
  x = [pad_window(s, window_size=window_size) for s in x]

  # Now we need to turn words in our training examples to indices. We are
  # copying the function defined earlier for the same reason as above.
  def convert_tokens_to_indices(sentence, word_to_ix):
    return [word_to_ix.get(token, word_to_ix["<unk>"]) for token in sentence]

  # Convert the train examples into indices.
  x = [convert_tokens_to_indices(s, word_to_ix) for s in x]

  # We will now pad the examples so that the lengths of all the example in
  # one batch are the same, making it possible to do matrix operations.
  # We set the batch_first parameter to True so that the returned matrix has
  # the batch as the first dimension.
  pad_token_ix = word_to_ix["<pad>"]

  # pad_sequence function expects the input to be a tensor, so we turn x into one
  x = [torch.LongTensor(x_i) for x_i in x]
  x_padded = nn.utils.rnn.pad_sequence(x, batch_first=True, padding_value=pad_token_ix) # 입력으로 써야하기에 문장 길이를 동일하게 맞춰줌

  # We will also pad the labels. Before doing so, we will record the number
  # of labels so that we know how many words existed in each example.
  lengths = [len(label) for label in y]
  lenghts = torch.LongTensor(lengths) 
# 각 단어마다 라벨링이 되기에 <pad>는 0으로 라벨링해서 길이 맞추기
  y = [torch.LongTensor(y_i) for y_i in y]
  y_padded = nn.utils.rnn.pad_sequence(y, batch_first=True, padding_value=0)

  # We are now ready to return our variables. The order we return our variables
  # here will match the order we read them in our training loop.
  return x_padded, y_padded, lenghts

This function seems long, but it really doesn't have to be. Check out the alternative version below where we remove the extra function declarations and comments.

In [72]:
def _custom_collate_fn(batch, window_size, word_to_ix):
  # Prepare the datapoints
  x, y = zip(*batch)
  x = [pad_window(s, window_size=window_size) for s in x]
  x = [convert_tokens_to_indices(s, word_to_ix) for s in x]

  # Pad x so that all the examples in the batch have the same size
  pad_token_ix = word_to_ix["<pad>"]
  x = [torch.LongTensor(x_i) for x_i in x]
  x_padded = nn.utils.rnn.pad_sequence(x, batch_first=True, padding_value=pad_token_ix)

  # Pad y and record the length
  lengths = [len(label) for label in y]
  lenghts = torch.LongTensor(lengths)
  y = [torch.LongTensor(y_i) for y_i in y]
  y_padded = nn.utils.rnn.pad_sequence(y, batch_first=True, padding_value=0)

  return x_padded, y_padded, lenghts

### `torch.utils.data.DataLoader`란?

`DataLoader`는 PyTorch에서 **데이터를 배치 단위로 자동으로 불러오고**,  
**모델에 넣기 편하게 구성**해주는 유틸리티 클래스이다.

---

### 주요 기능

- **배치 단위(batch-wise)**로 데이터 불러오기  
- **셔플(shuffling)** 기능 지원 → 데이터 순서를 무작위로 섞어 일반화 향상  
- **병렬 처리(num_workers)**로 데이터 로딩 속도 향상 가능  
- **이터레이터 형태**로 동작 → `for batch in dataloader:`처럼 사용 가능

---

### 왜 필요한가?

학습 시 데이터를 직접 한 줄씩 불러오는 것은 번거롭고 비효율적이다.  
`DataLoader`는 이를 자동화하여 **모델 학습을 더 효율적이고 안정적으로** 만들어 준다

---

### 요약

> ✅ `DataLoader`는 PyTorch에서 **모델 학습을 위한 데이터 관리와 배치 처리**를 도와주는 핵심 도구이다.


In [73]:
# Parameters to be passed to the DataLoader
data = list(zip(train_sentences, train_labels))
batch_size = 2
shuffle = True
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=window_size, word_to_ix=word_to_ix)

# Instantiate the DataLoader
loader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

# Go through one loop
counter = 0
for batched_x, batched_y, batched_lengths in loader:
  print(f"Iteration {counter}")
  print("Batched Input:")
  print(batched_x)
  print("Batched Labels:")
  print(batched_y)
  print("Batched Lengths:")
  print(batched_lengths)
  print("")
  counter += 1

Iteration 0
Batched Input:
tensor([[ 0,  0, 19,  5, 14, 21, 12,  3,  0,  0],
        [ 0,  0,  9,  7,  8, 18,  0,  0,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 1, 0, 1],
        [0, 0, 0, 1, 0, 0]])
Batched Lengths:
tensor([6, 4])

Iteration 1
Batched Input:
tensor([[ 0,  0, 19, 16, 12,  8,  4,  0,  0],
        [ 0,  0, 22,  2,  6, 20, 15,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1]])
Batched Lengths:
tensor([5, 5])

Iteration 2
Batched Input:
tensor([[ 0,  0, 10, 13, 11, 17,  0,  0]])
Batched Labels:
tensor([[0, 0, 0, 1]])
Batched Lengths:
tensor([4])



### 모델 입력: 윈도우 기반 분류기를 위한 전처리 완료

앞서 만든 배치 입력 텐서들은 이제 **모델에 전달될 준비**가 되었다.  
우리가 만들 모델은 **윈도우 기반 분류기(Window Classifier)**이다.

---

### 데이터 구조와 예측 방식

- 현재 입력된 텐서들은 **한 문장의 모든 단어가 하나의 데이터 포인트로 묶인 형태**이다.
- 모델은 이 데이터를 입력으로 받아 **각 단어를 중심으로 윈도우(window)**를 만들고,
- **중심 단어가 LOCATION인지 아닌지를 예측**해야 한다.
- 예측 결과는 **전체 문장에 대한 위치 정보(예: [0, 0, 0, 1])**로 반환된다.

---

### 윈도우 단위로 데이터를 미리 자를 수도 있지만...

- 데이터를 **사전에 윈도우 단위로 잘라 모델에 넣는 방식도 가능**하지만,  
- 이런 윈도우 생성 과정을 **모델 내부에서 처리**할 수도 있다.  
- 이 방식은 **모델을 더 일반적이고 유연하게** 만들어 준다.

---

### 윈도우 크기와 예측 횟수

- 윈도우 크기를 `N`이라고 하면, 매번 **2N + 1개의 단어**를 보고 예측을 수행
- 예시: 입력로 9개의 단어, 윈도우 크기 2 → 총 **5개의 예측 수행**

---

### 윈도우 생성: `unfold()` 메서드 활용

PyTorch에서는 **효율적으로 윈도우를 생성**할 수 있는 메서드가 존재한다:

```python
tensor.unfold(dimension, size, step)


In [74]:
# Print the original tensor
print(f"Original Tensor: ")
print(batched_x)
print("")

# Create the 2 * 2 + 1 chunks
chunk = batched_x.unfold(1, window_size*2 + 1, 1)
print(f"Windows: ")
print(chunk)

Original Tensor: 
tensor([[ 0,  0, 10, 13, 11, 17,  0,  0]])

Windows: 
tensor([[[ 0,  0, 10, 13, 11],
         [ 0, 10, 13, 11, 17],
         [10, 13, 11, 17,  0],
         [13, 11, 17,  0,  0]]])


### Model

Now that we have prepared our data, we are ready to build our model. We have learned how to write custom `nn.Module` classes. We will do the same here and put everything we have learned so far together.

In [ ]:
class WordWindowClassifier(nn.Module):

  def __init__(self, hyperparameters, vocab_size, pad_ix=0):
    super(WordWindowClassifier, self).__init__()

    """ Instance variables """
    self.window_size = hyperparameters["window_size"]
    self.embed_dim = hyperparameters["embed_dim"]
    self.hidden_dim = hyperparameters["hidden_dim"]
    self.freeze_embeddings = hyperparameters["freeze_embeddings"]

    """ Embedding Layer
    Takes in a tensor containing embedding indices, and returns the
    corresponding embeddings. The output is of dim
    (number_of_indices * embedding_dim).

    If freeze_embeddings is True, set the embedding layer parameters to be
    non-trainable. This is useful if we only want the parameters other than the
    embeddings parameters to change.

    """
    self.embeds = nn.Embedding(vocab_size, self.embed_dim, padding_idx=pad_ix)
    if self.freeze_embeddings:
      self.embed_layer.weight.requires_grad = False

    """ Hidden Layer
    """
    full_window_size = 2 * window_size + 1
    self.hidden_layer = nn.Sequential(
      nn.Linear(full_window_size * self.embed_dim, self.hidden_dim),
      nn.Tanh()
    )

    """ Output Layer
    """
    self.output_layer = nn.Linear(self.hidden_dim, 1)

    """ Probabilities
    """
    self.probabilities = nn.Sigmoid()

  def forward(self, inputs):
    """
    Let B:= batch_size
        L:= window-padded sentence length
        D:= self.embed_dim
        S:= self.window_size
        H:= self.hidden_dim

    inputs: a (B, L) tensor of token indices
    """
    B, L = inputs.size()

    """
    Reshaping.
    Takes in a (B, L) LongTensor
    Outputs a (B, L~, S) LongTensor
    """
    # Fist, get our word windows for each word in our input.
    token_windows = inputs.unfold(1, 2 * self.window_size + 1, 1)
    _, adjusted_length, _ = token_windows.size()

    # Good idea to do internal tensor-size sanity checks, at the least in comments!
    assert token_windows.size() == (B, adjusted_length, 2 * self.window_size + 1)

    """
    Embedding.
    Takes in a torch.LongTensor of size (B, L~, S)
    Outputs a (B, L~, S, D) FloatTensor.
    """
    embedded_windows = self.embeds(token_windows)

    """
    Reshaping.
    Takes in a (B, L~, S, D) FloatTensor.
    Resizes it into a (B, L~, S*D) FloatTensor.
    -1 argument "infers" what the last dimension should be based on leftover axes.
    """
    # nn.Linear에 넣기 위한 평탄화 작업 n*m(행렬)-> n*m(벡터) 
    embedded_windows = embedded_windows.view(B, adjusted_length, -1)

    """
    Layer 1.
    Takes in a (B, L~, S*D) FloatTensor.
    Resizes it into a (B, L~, H) FloatTensor
    """
    layer_1 = self.hidden_layer(embedded_windows)

    """
    Layer 2
    Takes in a (B, L~, H) FloatTensor.
    Resizes it into a (B, L~, 1) FloatTensor.
    """
    output = self.output_layer(layer_1)

    """
    Softmax.
    Takes in a (B, L~, 1) FloatTensor of unnormalized class scores.
    Outputs a (B, L~, 1) FloatTensor of (log-)normalized class scores.
    """
    output = self.probabilities(output)
    output = output.view(B, -1)

    return output

### 임베딩 벡터 평탄화(Flatten)란?
여러 개의 임베딩 벡터를 한 개의 긴 벡터로 이어 붙이는 것

### Training

We are now ready to put everything together. Let's start with preparing our data and intializing our model. We can then intialize our optimizer and define our loss function. This time, instead of using one of the predefined loss function as we did before, we will define our own loss function.

In [76]:
# Prepare the data
data = list(zip(train_sentences, train_labels))
batch_size = 2
shuffle = True
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=window_size, word_to_ix=word_to_ix)

# Instantiate a DataLoader
loader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

# Initialize a model
# It is useful to put all the model hyperparameters in a dictionary
model_hyperparameters = {
    "batch_size": 4,
    "window_size": 2,
    "embed_dim": 25,
    "hidden_dim": 25,
    "freeze_embeddings": False,
}

vocab_size = len(word_to_ix)
model = WordWindowClassifier(model_hyperparameters, vocab_size)

# Define an optimizer
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Define a loss function, which computes to binary cross entropy loss
def loss_function(batch_outputs, batch_labels, batch_lengths):
    # Calculate the loss for the whole batch
    bceloss = nn.BCELoss()
    loss = bceloss(batch_outputs, batch_labels.float())

    # Rescale the loss. Remember that we have used lengths to store the
    # number of words in each training example
    loss = loss / batch_lengths.sum().float()

    return loss

Unlike our earlier example, this time instead of passing all of our training data to the model at once in each epoch, we will be utilizing batches. Hence, in each training epoch iteration, we also iterate over the batches.

In [77]:
# Function that will be called in every epoch
def train_epoch(loss_function, optimizer, model, loader):

  # Keep track of the total loss for the batch
  total_loss = 0
  for batch_inputs, batch_labels, batch_lengths in loader:
    # Clear the gradients
    optimizer.zero_grad()
    # Run a forward pass
    outputs = model.forward(batch_inputs)
    # Compute the batch loss
    loss = loss_function(outputs, batch_labels, batch_lengths)
    # Calculate the gradients
    loss.backward()
    # Update the parameteres
    optimizer.step()
    total_loss += loss.item()

  return total_loss


# Function containing our main training loop
def train(loss_function, optimizer, model, loader, num_epochs=10000):

  # Iterate through each epoch and call our train_epoch function
  for epoch in range(num_epochs):
    epoch_loss = train_epoch(loss_function, optimizer, model, loader)
    if epoch % 100 == 0: print(epoch_loss)

Let's start training!

In [78]:
num_epochs = 1000
train(loss_function, optimizer, model, loader, num_epochs=num_epochs)

0.31150873750448227
0.2520594224333763
0.19919054582715034
0.14146507903933525
0.10948824509978294
0.07912580482661724
0.05796908866614103
0.04833683371543884
0.038688245229423046
0.03507177997380495


### Prediction

Let's see how well our model is at making predictions. We can start by creating our test data.

In [79]:
# Create test sentences
test_corpus = ["She comes from Paris"]
test_sentences = [s.lower().split() for s in test_corpus]
test_labels = [[0, 0, 0, 1]]

# Create a test loader
test_data = list(zip(test_sentences, test_labels))
batch_size = 1
shuffle = False
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=2, word_to_ix=word_to_ix)
test_loader = torch.utils.data.DataLoader(test_data,
                                           batch_size=1,
                                           shuffle=False,
                                           collate_fn=collate_fn)

Let's loop over our test examples to see how well we are doing.

In [80]:
for test_instance, labels, _ in test_loader:
  outputs = model.forward(test_instance)
  print(labels)
  print(outputs)

tensor([[0, 0, 0, 1]])
tensor([[0.0791, 0.0237, 0.0254, 0.9709]], grad_fn=<ViewBackward0>)
